---
- name: download foo.conf
  get_url:
    url: https://camunda.org/release/camunda-bpm/tomcat/7.6/camunda-bpm-tomcat-7.6.0.tar.gz
    dest: /opt/camunda-bpm-tomcat-7.6.0.tar.gz

- file:
    path: /opt/camunda-bpm-tomcat-7.6.0
    state: directory

- unarchive:
    src: /opt/camunda-bpm-tomcat-7.6.0.tar.gz
    dest: /opt/camunda-bpm-tomcat-7.6.0
#- name: Download camunda tomcate some dependencies
#  shell: curl -O https://camunda.org/release/camunda-bpm/tomcat/7.6/camunda-bpm-tomcat-7.6.0.tar.gz

#- shell: tar -xzvf camunda-bpm-tomcat-7.6.0.tar.gz

- name: Start tomcat
  shell: sh /opt/camunda-bpm-tomcat-7.6.0/start-camunda.sh
