---
- name: installing some dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - git
  - curl
  - vim
#  - libssl0.9.8
#  - libjna-java
#  - sysstat
#  - python-software-properties
